from __future__ import annotations
from dataclasses import dataclass


@dataclass(slots=True)
class Packet:
    """A lightweight IoT data packet generated by one node."""
    packet_id: int
    node_id: int
    created_at: int
    size_kb: float
    priority: int
    importance_weight: float
